# Generated by Django 2.2.1 on 2019-12-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseNumber', models.CharField(max_length=64)),
                ('executionstate', models.CharField(max_length=64)),
                ('Insurance', models.CharField(max_length=64)),
                ('sceneid', models.CharField(max_length=64)),
                ('sagent', models.CharField(max_length=64)),
                ('xagent', models.CharField(max_length=64)),
                ('founder', models.CharField(max_length=64)),
                ('creationtime', models.CharField(max_length=64)),
            ],
        ),
    ]
