# Generated by Django 2.2.1 on 2019-12-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfirst_step', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseno', models.CharField(max_length=64)),
                ('Insurance', models.CharField(max_length=64)),
                ('cictcode', models.CharField(max_length=64)),
                ('renewal', models.CharField(max_length=64)),
                ('offer', models.CharField(max_length=64)),
                ('sceneid', models.CharField(max_length=64)),
                ('details', models.CharField(max_length=64)),
                ('ontrast', models.CharField(max_length=64)),
                ('insuredcontrast', models.CharField(max_length=64)),
            ],
        ),
    ]
