# Generated by Django 2.2.1 on 2019-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfirst_step', '0002_data_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_details',
            name='strip',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
    ]
